import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@cubik/presets/styles/style.css";
import "@cubik/presets/styles/lightColor.style.css";
import "@cubik/presets/styles/darkColors.styles.css";
import "@cubik/presets/styles/component.style.css";

import Sidebar from "./components/sidebar";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="light" lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex flex-row w-full">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
